---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "terraform/module1/"
    schedule: 
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "terraform/module2/"
    schedule: 
      interval: "daily"      
