---
version: 2

registries:
 version-source-mod1:
   type: terraform-registry
   url: https://github.com/viccro/version-source/ #/module1
   token: ${{ secrets.VERSION_SOURCE_TOKEN}}

updates:
 - package-ecosystem: "terraform"
   directory: "/module1"
   registries:
     - version-source-mod1
   schedule:
     interval: "daily"
